### ISSUE TITLE
[디자인] 열혈무군 디자인 스타일 작업

### ISSUE THREAD

**Issue by dltkddns833** [dltkddns833/YHMG#1]
열혈무군 사이트 내 컬러 팔레트 & 폰트 정하기

## TODO
- [x] Main color(Primary color) 
- [x] Secondary Color(Point color)
- [x] Font Style

## DONE

**Comment by dltkddns833** [comment]
예시)
[MUI]
https://mui.com/material-ui/customization/color/#color-palette

**Comment by dltkddns833** [comment]
@Joo00h 

Color Theme & Typography 예시(Figma 정리된거)

![Image](https://user-images.githubusercontent.com/20149239/223021858-7f500a36-519c-4507-acfa-84063b8fea3c.png)
![Image](https://user-images.githubusercontent.com/20149239/223021857-2bff62da-b52c-4394-8ae0-d534e74f3103.png)

**Comment by Joo00h** [comment]
![image](https://user-images.githubusercontent.com/127005448/224520893-a3131968-0f58-4ba9-b237-baa04fbdf661.png)

개인적으로 볼드하고 심플한 느낌이 들었으면 좋겠어서, 명도 채도로 컬러 베리에이션 나누는 것은 많이 안 써도 좋을 것 같아용
원밀리언 홈페이지처럼, 오퍼시티 따로 주지 않고 가장 상단의 컬러 중심으로 진행하는 것도 좋을 것 같습니당
디자인 하는 과정에서 컬러가 더 필요하다고 판단되면 그 때 더 추가하도록 하겠습니닷

**Comment by Joo00h** [comment]
![image](https://user-images.githubusercontent.com/127005448/224521058-8f1c5ed0-02aa-4fa7-ba78-8f8fa00058a6.png)

고민.. 중..
홈페이지 방향성을 어떻게 가져가느냐에 따라 달라질 것 같아요
아예 러프한 컨셉 / 심플하고 볼드한 컨셉 / 일러스트 친근한 컨셉 등
전반적인 컨셉 어떻게 할지 좀 더 고민해보면 좋을 것 같습니당

**Comment by Joo00h** [comment]
한글폰트 보충 (ex: Happiness Sans)
