### ISSUE TITLE
[디자인] Figma 프로젝트 생성

### ISSUE THREAD

**Issue by dltkddns833** [dltkddns833/YHMG#2]
## TODO
- [ ] Figma 프로젝트 생성
- [ ] 디자인 스타일 Figma로 정리

## DONE

**Comment by dltkddns833** [comment]
@Joo00h  피그마 링크 주세용

**Comment by Joo00h** [comment]
https://www.figma.com/file/j3pzMllKQHQzxUtAX6NgA1/%EC%97%B4%ED%98%88%EB%AC%B4%EA%B5%B0?node-id=0-1&t=nQ53P922B2fhdsnT-0
요기 있습니다~!
