### ISSUE TITLE
[디자인] 레퍼런스 사이트 조사

### ISSUE THREAD

**Issue by dltkddns833** [dltkddns833/YHMG#3]
관련 레퍼런스 Comment로 정리

## TODO
- [x] #8

## DONE

**Comment by Joo00h** [comment]
https://www.behance.net/gallery/113457767/Kangol-Website-E-commerce
https://www.behance.net/gallery/107641795/Nike-Website-UI-Concept
https://www.studiobrot.de/
https://wearezak.com/
https://ohm.studio/
