### ISSUE TITLE
[개발] React Typescript 프로젝트 생성

### ISSUE THREAD

**Issue by dltkddns833** [dltkddns833/YHMG#4]
## TODO
- [ ] Scroll 라이브러리 조사
- [ ] 개발 프로젝트 생성하여 YHMG Github에 upload
- [ ] MUI 설치

**Comment by joonyy** [comment]
### Scroll 라이브러리
- ScrollMagic
- AOS
---
학습 후 직접 적용해볼 수 있을 때 추가 조사 예정

**Comment by dltkddns833** [comment]
@dltkddns833 

프로젝트 생성을 제가 하겠습니다.
