### ISSUE TITLE
[운영] 디자인&개발 레퍼런스 전달

### ISSUE THREAD

**Issue by dltkddns833** [dltkddns833/YHMG#6]
## TODO
- [x] 컬러 팔레트 정리된 Figma 레퍼런스 전달
- [x] 개발도서(React Typescript) 추천
## DONE

**Comment by dltkddns833** [comment]
디자인 레퍼런스
https://github.com/dltkddns833/YHMG/issues/1#issuecomment-1455445172

**Comment by dltkddns833** [comment]
리액트 책 추천 @joonyy 
https://product.kyobobook.co.kr/detail/S000001792882

**Comment by joonyy** [comment]
@dltkddns833 감사합니다 바로 주문했습니다 분발하겠습니다!
