### ISSUE TITLE
[운영] 기획 참여 가능 여부 조사

### ISSUE THREAD

**Issue by dltkddns833** [dltkddns833/YHMG#7]
## TODO
- [ ] 열혈무군 운영진들 기획 참여 가능여부 물어보기
## NEXT
- [ ] 요구사항 명세 작성
## DONE

**Comment by Joo00h** [comment]
현재 기획 관련 데이터가 암것도 없다보니 디자인을 대충 어떤 식으로 잡아야 할지 감이 잘 안 와서요..!
대략적으로 메뉴 구성 해 보았습니다

ABOUT YHMG
JOIN OUR TEAM
SCHEDULE
VIDEOS
REELS/SHORTS
NEWS
FAQ

메인페이지만 따로 구성해서 메뉴를 모두 서브페이지로 뺄 것인지, 혹은
스크롤 내리면 각 메뉴를 간략하게 볼 수 있게 할 것인지 정해도 좋을 것 같아요

**Comment by dltkddns833** [comment]
![Image](https://user-images.githubusercontent.com/20149239/225833791-0062a5d5-060a-4173-ae1d-ced15030d254.png)

**Comment by dltkddns833** [comment]
현 간부진의 도움이 매우 어려워 보임 (개강, 신입 동아리원 모집 등으로 매우 바쁘다고 함)
-> 기획부장 참여 유도중

**Comment by joonyy** [comment]
@dltkddns833 회의 때 저희끼리 기획해서 요구명세를 뽑아두는건 무리일까요???

**Comment by Joo00h** [comment]
요고는 로고 파일 받다가 작년 홍보부장 친구한테 한번 물어봤던 것이어용
![image](https://user-images.githubusercontent.com/127005448/226151642-3fb99032-4ac3-4858-ab1d-4b4a46cc87b5.png)
